# DATA PREPROCESSING/DATA PREPARATION

1. Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype
2. Data Transformation
    * If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
    * If data is DISCRETE   = Label Encoder, One hot Encoder

## 1. Import Necessary Libraries

In [3]:
import pandas as pd

## 2. Import Dataset

In [4]:
weather_data = pd.read_csv("environmental_data.csv")
weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

## 3. Data Understanding

### 3.1 Perform Initial Analysis on the Data

In [5]:
weather_data.shape

(158, 10)

In [6]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [6]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [7]:
weather_data.describe(include="all") # include = "all" for get the all columns

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [8]:
weather_data["Weather"].unique() # unique is used to fetch all the values of Weather cloumn

array(['S', 'C', 'PS', nan], dtype=object)

In [9]:
weather_data["Weather"].value_counts(dropna = False) # value_counts is used to provide the values of each Weather cloumn values. # dropna = False - inculde nan values

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

## 4. Data Preparation

### Stage 1 - Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype

In [ ]:
### In Data pre-processing face in 
** stage 1 - remove uncessary columns and remove null entries for that try to check whether mean, median, mode entiers can be updated.

In [10]:
weather_data.head(10)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S
5           6   28.0      NaN  14.9     66     5    6  2010    66       C
6           7   23.0    299.0   8.6     65     5    7  2010    65      PS
7           8   19.0     99.0  13.8     59     5    8  2010    59       C
8           9    8.0     19.0  20.1     61     5    9  2010    61      PS
9          10    NaN    194.0   8.6     69     5   10  2010    69       S

In [11]:
weather_data.drop(labels = ["Unnamed: 0","Temp C"],axis = 1,inplace=True) 

# Since Unmaned and Temp C columns seems to be duplicate we need to remove it.
# .drop() - used to remove mutliple columns
# axis = 1 - removing column
# inplace = True - used to mention where data will be unchanged further

In [12]:
weather_data.head(15)

    Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0    41.0    190.0   7.4     5    1  2010    67       S
1    36.0    118.0   8.0     5    2  2010    72       C
2    12.0    149.0  12.6     5    3  2010    74      PS
3    18.0    313.0  11.5     5    4  2010    62       S
4     NaN      NaN  14.3     5    5  2010    56       S
5    28.0      NaN  14.9     5    6  2010    66       C
6    23.0    299.0   8.6     5    7  2010    65      PS
7    19.0     99.0  13.8     5    8  2010    59       C
8     8.0     19.0  20.1     5    9  2010    61      PS
9     NaN    194.0   8.6     5   10  2010    69       S
10    7.0      NaN   6.9     5   11  2010    74       C
11   16.0    256.0   9.7     5   12  2010    69      PS
12   11.0    290.0   9.2     5   13  2010    66       S
13   14.0    274.0  10.9     5   14  2010    68       S
14   18.0     65.0  13.2     5   15  2010    58       C

### We removed unwanted columns - UnNamed 0, and Temp C.

In [13]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [22]:
weather_data.shape

(158, 8)

In [23]:
38/158  # Since 24% data are null for "Ozone" cloumn we need to check with team lead or client and get approval to remove the null values else we need get propoer data set from client

0.24050632911392406

### I'm dropping this column, as 25% of the data is NaN.

In [14]:
del weather_data["Ozone"] # For removing one column we can use del

In [15]:
weather_data.isna().sum() # Solar.R has 7 null entries

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [16]:
weather_data.head(15)

    Solar.R  Wind Month  Day  Year  Temp Weather
0     190.0   7.4     5    1  2010    67       S
1     118.0   8.0     5    2  2010    72       C
2     149.0  12.6     5    3  2010    74      PS
3     313.0  11.5     5    4  2010    62       S
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
6     299.0   8.6     5    7  2010    65      PS
7      99.0  13.8     5    8  2010    59       C
8      19.0  20.1     5    9  2010    61      PS
9     194.0   8.6     5   10  2010    69       S
10      NaN   6.9     5   11  2010    74       C
11    256.0   9.7     5   12  2010    69      PS
12    290.0   9.2     5   13  2010    66       S
13    274.0  10.9     5   14  2010    68       S
14     65.0  13.2     5   15  2010    58       C

In [29]:
7/158

0.04430379746835443

In [17]:
weather_data[weather_data["Solar.R"].isna()] # Now lets check the 7 null entried of Solar.R data

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [18]:
weather_data.groupby("Weather")["Solar.R"].mean().round() 

# Since Solar. R has 7 null entries and Weather has 2 Sunny( S), 3 Cloudy(C), one Partial Sunnay(PS) and 1 null entry
# We need to make common mean value for Solar. R null values for C,PS,S
# So we need to use mean func

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [21]:
weather_data["Solar.R"] = weather_data.groupby("Weather")["Solar.R"].transform(lambda x:x.fillna(x.mean().round()))
weather_data

# Instead of filling all missing values with one overall average, this code fills them based on the average Solar.R for that particular Weather group.
# For each Weather group, look only at the Solar.R column.
# Now we need to transfer the mean values to Solar.R Column so we need to use groupby.
# transform()calculates something within each group and returns a result with the same number of rows as the original data.
# lambda x - Here x represents the Solar.R values for one Weather group.
# x.mean().round() - Finds the average Solar.R for that particular Weather group and rounds it.

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [39]:
weather_data.isna().sum() # Post transforming mean value now re-check and again we find 3 null value for Solar.R

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [40]:
weather_data[weather_data["Solar.R"].isna()] # Now check the null values for Solar.R

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [22]:
weather_data.dropna(inplace=True) 

# since Solar R and Weather column seems to be Null values and mainly o/p value (Weather) seems to have null values , better to remove those 3 null values

In [43]:
weather_data.isna().sum() # Now data is clean without Null values

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [44]:
weather_data.shape

(155, 7)

In [45]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [46]:
weather_data["Month"].unique() 

# Since Month column seems to be object , we need to check their unique values
# in numberic value even "May" is inculded

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [48]:
weather_data.head(30)

    Solar.R  Wind Month  Day  Year  Temp Weather
0     190.0   7.4     5    1  2010    67       S
1     118.0   8.0     5    2  2010    72       C
2     149.0  12.6     5    3  2010    74      PS
3     313.0  11.5     5    4  2010    62       S
4     193.0  14.3     5    5  2010    56       S
5     192.0  14.9     5    6  2010    66       C
6     299.0   8.6     5    7  2010    65      PS
7      99.0  13.8     5    8  2010    59       C
8      19.0  20.1     5    9  2010    61      PS
9     194.0   8.6     5   10  2010    69       S
10    192.0   6.9     5   11  2010    74       C
11    256.0   9.7     5   12  2010    69      PS
12    290.0   9.2     5   13  2010    66       S
13    274.0  10.9     5   14  2010    68       S
14     65.0  13.2     5   15  2010    58       C
15    334.0  11.5     5   16  2010    64       S
16    307.0  12.0     5   17  2010    66       S
17     78.0  18.4     5   18  2010    57       C
18    322.0  11.5     5   19  2010    68      PS
19     44.0   9.7     5   20  2010    62       S
20      8.0   9.7     5   21  2010    59       S
21    320.0  16.6     5   22  2010    73       C
22     25.0   9.7     5   23  2010    61      PS
23     92.0  12.0   May   24  2010    61       C
24     66.0  16.6     5   25  2010    57      PS
25    266.0  14.9     5   26  2010    58       C
26    174.0   8.0     5   27  2010    57      PS
27     13.0  12.0     5   28  2010    67       S
28    252.0  14.9     5   29  2010    81       S
29    223.0   5.7     5   30  2010    79       C

In [52]:
import warnings
warnings.filterwarnings("ignore") # Ignoring warnings

In [53]:
weather_data["Month"].replace(to_replace="May",value=5, inplace = True) 

# While checking the Month value we found 'May" and we can replace it to numberic as 5 value

In [54]:
weather_data.head(30)

    Solar.R  Wind Month  Day  Year  Temp Weather
0     190.0   7.4     5    1  2010    67       S
1     118.0   8.0     5    2  2010    72       C
2     149.0  12.6     5    3  2010    74      PS
3     313.0  11.5     5    4  2010    62       S
4     193.0  14.3     5    5  2010    56       S
5     192.0  14.9     5    6  2010    66       C
6     299.0   8.6     5    7  2010    65      PS
7      99.0  13.8     5    8  2010    59       C
8      19.0  20.1     5    9  2010    61      PS
9     194.0   8.6     5   10  2010    69       S
10    192.0   6.9     5   11  2010    74       C
11    256.0   9.7     5   12  2010    69      PS
12    290.0   9.2     5   13  2010    66       S
13    274.0  10.9     5   14  2010    68       S
14     65.0  13.2     5   15  2010    58       C
15    334.0  11.5     5   16  2010    64       S
16    307.0  12.0     5   17  2010    66       S
17     78.0  18.4     5   18  2010    57       C
18    322.0  11.5     5   19  2010    68      PS
19     44.0   9.7     5   20  2010    62       S
20      8.0   9.7     5   21  2010    59       S
21    320.0  16.6     5   22  2010    73       C
22     25.0   9.7     5   23  2010    61      PS
23     92.0  12.0     5   24  2010    61       C
24     66.0  16.6     5   25  2010    57      PS
25    266.0  14.9     5   26  2010    58       C
26    174.0   8.0     5   27  2010    57      PS
27     13.0  12.0     5   28  2010    67       S
28    252.0  14.9     5   29  2010    81       S
29    223.0   5.7     5   30  2010    79       C

In [55]:
weather_data.dtypes # Now checking the data types again, however Month remains dtypes as Object

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [57]:
weather_data["Month"] = weather_data["Month"].astype("int") # To change the dtypes we are using astype as "int"
weather_data

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [58]:
weather_data.dtypes # now dtypes for Month is changed

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

#### Here Ends the Data Cleaning

## Stage 2

### 2. Data Transformation
    * If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
    * If data is DISCRETE   = Label Encoder, One hot Encoder

In [59]:
weather_data

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

### Since Weather (o/p) Column had discreate means catoery we need to change them to numberic pattern since machine will understand numberic values

* Column	Type
* Solar.R	Continuous numerical
* Wind	Continuous numerical
* Month	Discrete numerical (or categorical, depending on how you use it)
* Day	Discrete numerical
* Year	Discrete numerical
* Temp	Continuous numerical
* Weather	Categorical ✅

#### Before transforming  the values into numberic make sure we are taking one copy

In [27]:
weather_data_copy_01 = weather_data.copy()
weather_data_copy_01

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[155 rows x 7 columns]

#### We use this below code because machine learning models generally need numerical input, but your Weather column contains text categories:
Weather
-------
S
C
PS
S
C

# So we convert the categories into numbers

In [28]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
le_encoder.fit_transform(weather_data_copy_01["Weather"])

array([2, 0, 1, 2, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0,
       1, 0, 1, 0, 1, 2, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2,
       2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2,
       0, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2, 0, 1, 0, 2, 2, 0, 1, 1, 0, 2,
       0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 2, 2, 2, 0, 0, 0, 1, 0, 1, 2, 2,
       0, 1, 0, 1, 2, 2, 2, 2, 2, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1, 0, 1, 2,
       2, 1, 1, 2, 1, 2, 0, 1, 1, 2, 2, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 2,
       0])

In [29]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
weather_data_copy_01["Weather"]= le_encoder.fit_transform(weather_data_copy_01["Weather"])
weather_data_copy_01

# from sklearn.preprocessing import LabelEncoder - This imports the tool that converts categorical labels into numbers.
# le_encoder = LabelEncoder() - Here, le_encoder is just a variable that stores the encoder.
# encode the values in alhabatic order 
# and updating it in orginal data weather_data_copy_01

# C - 0 
# PS -1
# S - 2

     Solar.R  Wind Month  Day  Year  Temp  Weather
0      190.0   7.4     5    1  2010    67        2
1      118.0   8.0     5    2  2010    72        0
2      149.0  12.6     5    3  2010    74        1
3      313.0  11.5     5    4  2010    62        2
4      193.0  14.3     5    5  2010    56        2
..       ...   ...   ...  ...   ...   ...      ...
153    190.0   7.4     5    1  2010    67        0
154    193.0   6.9     9   26  2010    70        1
155    145.0  13.2     9   27  2010    77        2
156    191.0  14.3     9   28  2010    75        2
157    131.0   8.0     9   29  2010    76        0

[155 rows x 7 columns]

In [66]:
weather_data_copy_01.dtypes # Check the data type now

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

### 2. One Hot Encoder

This can be achieved by using any of the following 2 libraries:

1. Pandas - pd.get_dummies()
2. sklearn - OneHotEncoder()

#### 1. Pandas - pd.get_dummies()

In [ ]:
# making another copy

In [38]:
weather_data_copy_02 = weather_data.copy()
weather_data_copy_02

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[155 rows x 7 columns]

In [39]:
pd.get_dummies(data = weather_data_copy_02,columns=["Weather"]) # Provide new cloumns of each catoegiers of Weather o/p

     Solar.R  Wind Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4     5    1  2010    67      False       False       True
1      118.0   8.0     5    2  2010    72       True       False      False
2      149.0  12.6     5    3  2010    74      False        True      False
3      313.0  11.5     5    4  2010    62      False       False       True
4      193.0  14.3     5    5  2010    56      False       False       True
..       ...   ...   ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4     5    1  2010    67       True       False      False
154    193.0   6.9     9   26  2010    70      False        True      False
155    145.0  13.2     9   27  2010    77      False       False       True
156    191.0  14.3     9   28  2010    75      False       False       True
157    131.0   8.0     9   29  2010    76       True       False      False

[155 rows x 9 columns]

In [40]:
weather_data_copy_02 = pd.get_dummies(data = weather_data_copy_02,columns=["Weather"],dtype = "int")
weather_data_copy_02

# now new column catoerfy true or false value changed to numeric value int

     Solar.R  Wind Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4     5    1  2010    67          0           0          1
1      118.0   8.0     5    2  2010    72          1           0          0
2      149.0  12.6     5    3  2010    74          0           1          0
3      313.0  11.5     5    4  2010    62          0           0          1
4      193.0  14.3     5    5  2010    56          0           0          1
..       ...   ...   ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4     5    1  2010    67          1           0          0
154    193.0   6.9     9   26  2010    70          0           1          0
155    145.0  13.2     9   27  2010    77          0           0          1
156    191.0  14.3     9   28  2010    75          0           0          1
157    131.0   8.0     9   29  2010    76          1           0          0

[155 rows x 9 columns]

In [41]:
weather_data_copy_02.dtypes

Solar.R       float64
Wind          float64
Month          object
Day             int64
Year            int64
Temp            int64
Weather_C       int64
Weather_PS      int64
Weather_S       int64
dtype: object

In [36]:
weather_data_copy_02 = pd.get_dummies(data = weather_data_copy_02,columns=["Weather"],dtype = "int",drop_first = True)
weather_data_copy_02

     Solar.R  Wind Month  Day  Year  Temp  Weather_PS  Weather_S
0      190.0   7.4     5    1  2010    67           0          1
1      118.0   8.0     5    2  2010    72           0          0
2      149.0  12.6     5    3  2010    74           1          0
3      313.0  11.5     5    4  2010    62           0          1
4      193.0  14.3     5    5  2010    56           0          1
..       ...   ...   ...  ...   ...   ...         ...        ...
153    190.0   7.4     5    1  2010    67           0          0
154    193.0   6.9     9   26  2010    70           1          0
155    145.0  13.2     9   27  2010    77           0          1
156    191.0  14.3     9   28  2010    75           0          1
157    131.0   8.0     9   29  2010    76           0          0

[155 rows x 8 columns]

In [78]:
weather_data_copy_02.dtypes

Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather_C       int64
Weather_PS      int64
Weather_S       int64
dtype: object

### 2. sklearn - OneHotEncoder() ( Alternate)

In [79]:
weather_data_copy_03 = weather_data.copy()
weather_data_copy_03

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [83]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
weather_data_copy_03 = ohe.fit_transform(weather_data_copy_03["Weather"])
weather_data_copy_03

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

## =========================================================

## What is Label Encoder and One Hot Encoder ?

* Both are used to convert categorical data into numerical form so machine learning algorithms can work with it.

### 1. Label Encoder

### Label Encoding converts each category into a single number.

# Example:

Weather
-------
C
PS
S
C

# After Label Encoding:

C  → 0
PS → 1
S  → 2

### When do we use LabelEncoder?

# It is commonly used for the target variable (y) o/p in classification.

# Example:

# Weather
C  → 0
PS → 1
S  → 2

# The model predicts one of these classes.

### 2. One-Hot Encoder

### One-Hot Encoding creates a separate column for each category.

# Original:

# Weather
-------
C
PS
S

# After One-Hot Encoding:

# Weather_C	Weather_PS	Weather_S
1	0	0
0	1	0
0	0	1

### Why is One-Hot Encoding useful?

# It avoids creating a false numerical relationship.

# With Label Encoding:

C  = 0
PS = 1
S  = 2

# A model might incorrectly interpret:

S > PS > C

# But these are just categories. There isn't really a numerical relationship.

# One-Hot Encoding avoids this:

C  → [1, 0, 0]
PS → [0, 1, 0]
S  → [0, 0, 1]

### When type of data is discrete we can use Label encoder and one hot encoder

## How to choose between Label Encoder and One Hot Encoder?

### Input feature:
Based on whether it is **Parametric or a Non Parametric Model**, we will choosing between LE or OHE.
* For **Parametric Models** - better to go with **OHE.**
* For **Non-Parametric Models** - always go with **Label Encoding.**

### Output feature:
Always the output feature, it must be **Label Encoder.**

## =========================================================

# Easy comparison
                                       Label Encoder	               One-Hot Encoder
# Converts categories to numbers?	   ✅	                           ✅
# Number of columns	                   1	                            Multiple
# Example	                         C → 0	                            C → [1,0,0]
# Good for target y	                 ✅ Commonly	                  Sometimes
# Good for input features X	         ⚠️ Depends	                      ✅ Commonly
# Creates numerical order?	         Yes, potentially misleading	   No

## THE END!!!

In [ ]:
Raw Data
   ↓
1. Understand Data
   ↓
2. Clean Data
   ↓
3. Handle Missing Values
   ↓
4. Remove Duplicates
   ↓
5. Handle Outliers
   ↓
6. Encode Categorical Data
   ↓
7. Scale Numerical Data
   ↓
8. Feature Selection / Engineering
   ↓
9. Train-Test Split
   ↓
10. Build Model

In [ ]:
# Data preprocessing is the process of preparing raw data for machine learning. The main steps are understanding the data, handling missing values and duplicates, treating outliers, encoding categorical variables, scaling numerical features when required, performing feature selection or engineering, and splitting the data into training and testing sets.

# 1. Understand the data

First check:

* df.head()
* df.shape
* df.info()
* df.describe()
* df.dtypes

# We want to know:

* How many rows and columns?
* Numerical or categorical?
* Missing values?
* Wrong data types?
* Target variable?

# 2. Handle Missing Values

Example:

Age
---
25
30
NaN
40

We can:

Fill it:

df["Age"].fillna(df["Age"].mean())

or remove it:

df.dropna()
    
# 3. Remove Duplicates
df.drop_duplicates()

Duplicate records can affect model performance.

# 4. Handle Outliers

Example:

Age:
20, 25, 30, 35, 40, 500

500 is probably an outlier/error.

We can identify outliers using:

Boxplot
IQR
Z-score

Then decide whether to remove, cap, transform, or keep them.

# 5. Encode Categorical Variables

Machine learning models generally need numerical input.

Example:

Weather
S
C
PS

For nominal input features, commonly use One-Hot Encoding:

Weather_C  Weather_PS  Weather_S
1          0           0
0          1           0
0          0           1

For a classification target, Label Encoding is commonly used:

C  → 0
PS → 1
S  → 2

# 6. Feature Scaling

Some algorithms are sensitive to the scale of numerical features.

Example:

Age     → 20–80
Salary  → 20,000–200,000

We can use:

StandardScaler()

or:

MinMaxScaler()

Scaling is particularly important for models such as:

Logistic Regression
KNN
SVM
K-Means

Tree-based models generally don't require feature scaling.

# 7. Feature Selection / Engineering

Choose useful features and possibly create new ones.

Example:

Height + Weight
       ↓
BMI

Remove unnecessary columns if appropriate.

# 8. Train-Test Split

Separate the data into training and testing sets:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

For example:

80% → Training
20% → Testing