## 1. Import Necessary Libraries

In [59]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

## 2. Import Dataset

In [38]:
claimants_data = pd.read_csv("claimants.csv")
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

## 3. Data Understanding

In [4]:
claimants_data.shape

(1340, 7)

In [5]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [6]:
claimants_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

## 4. Data Preparation

### 4.1 Data Cleaning

In [62]:
claimants_data.dropna(inplace = True)

In [9]:
1340-1096

244

In [63]:
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1334    34104         1     1.0       1.0       0.0    16.0   0.060
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1096 rows x 7 columns]

In [64]:
claimants_data.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

## 4.2 Seperate your inputs and Outputs

In [66]:
X = claimants_data.drop(labels = ["CASENUM","ATTORNEY"],axis = 1,)
X

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [67]:
y = claimants_data["ATTORNEY"]
y

0       0
1       1
2       1
3       0
4       1
       ..
1334    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1096, dtype: int64

## 5. Model Building

In [68]:
train_test_split(X,y,test_size = 0.20,shuffle=True)    #  [1072 rows x 5 columns] - 80% of data trained
                                                                                       #  [268 rows x 5 columns] - 20% of data tested

[      CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
 26       0.0       1.0       0.0    61.0  0.150
 1282     1.0       1.0       0.0     0.0  0.067
 346      1.0       0.0       0.0    61.0  0.830
 551      0.0       0.0       0.0    16.0  0.830
 980      1.0       1.0       0.0     6.0  0.757
 ...      ...       ...       ...     ...    ...
 832      1.0       1.0       0.0    43.0  4.088
 542      0.0       1.0       0.0    56.0  3.010
 752      1.0       1.0       0.0    39.0  4.095
 1287     0.0       0.0       0.0    10.0  0.040
 1014     0.0       1.0       0.0     7.0  7.180

 [876 rows x 5 columns],
       CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
 190      1.0       1.0       0.0    14.0  1.595
 877      0.0       1.0       0.0    37.0  8.075
 161      0.0       1.0       0.0    10.0  0.375
 741      1.0       1.0       0.0    30.0  5.010
 837      1.0       1.0       0.0    44.0  0.486
 ...      ...       ...       ...     ...    ...
 711      1.0       1.0       0.0    40.0  5.967
 33       1.0       1.0       0.0    35.0  1.673
 1202     1.0       1.0       0.0    11.0  0.436
 731      0.0       1.0       0.0    30.0  4.014
 1281     0.0       1.0       0.0    30.0  3.735

 [220 rows x 5 columns],
 26      1
 1282    0
 346     1
 551     0
 980     1
        ..
 832     1
 542     0
 752     1
 1287    1
 1014    1
 Name: ATTORNEY, Length: 876, dtype: int64,
 190     1
 877     1
 161     1
 741     0
 837     0
        ..
 711     1
 33      0
 1202    1
 731     0
 1281    0
 Name: ATTORNEY, Length: 220, dtype: int64]

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.20,shuffle=True,random_state= 34) # Storing the data in X_train, X_test, y_train, y_test

# random_state fixes the random shuffling, so the training and testing data don't change every time we run the program.Any postive no can be given

In [100]:
X_train  # 1072 rows × 5 columns - 80% data trained

     CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
478     0.0       1.0       1.0    10.0   1.318
387     1.0       1.0       0.0    55.0   0.604
47      0.0       1.0       0.0     1.0   0.000
220     1.0       1.0       1.0     7.0   0.983
152     1.0       1.0       0.0     6.0   0.075
..      ...       ...       ...     ...     ...
731     0.0       1.0       0.0    30.0   4.014
817     0.0       1.0       0.0    48.0   0.390
557     0.0       1.0       0.0    30.0   0.565
386     1.0       1.0       0.0    35.0   0.860
599     1.0       1.0       0.0    37.0  63.361

[876 rows x 5 columns]

In [101]:
X_test # 220 rows × 5 columns - 20% data tested

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
627      1.0       1.0       0.0    40.0  6.337
1125     1.0       1.0       0.0    37.0  4.609
1124     1.0       1.0       0.0    46.0  0.730
1025     1.0       1.0       0.0    38.0  3.406
481      1.0       1.0       0.0    70.0  0.566
...      ...       ...       ...     ...    ...
658      0.0       1.0       0.0    14.0  4.479
1257     0.0       1.0       0.0     7.0  0.453
1015     1.0       0.0       0.0    69.0  3.110
1114     1.0       1.0       0.0     0.0  7.169
990      1.0       1.0       0.0    43.0  8.490

[220 rows x 5 columns]

In [102]:
logistic_model = LogisticRegression()

## 6. Model Training

In [103]:
logistic_model.fit(X_train,y_train)

LogisticRegression()

## 7. Model Testing

### Training Data

In [104]:
y_pred_train = logistic_model.predict(X_train)
y_pred_train

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0])

### Test Data

In [105]:
y_pred_test = logistic_model.predict(X_test)
y_pred_test

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0])

## 8. Model Evaluation

In [106]:
from sklearn.metrics import accuracy_score

### Training Accurancy

In [107]:
accuracy_score(y_train,y_pred_train)

0.708904109589041

### Test Accurancy

In [108]:
accuracy_score(y_test,y_pred_test)

0.6818181818181818

## 9. Model Deployment

In [109]:
from pickle import dump

In [110]:
dump(logistic_model,open("claimaints.pkl","wb"))

## THE END!!